name: Release

on: 
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  release:
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}