name: Tag release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  quality:
    uses: ./.github/workflows/_test_publish.yml
    secrest:
      PYPI_TOKEN: {{ secrets.PYPI_TOKEN }}

